version: '3.7'
services: 
   prod_app_311:
      container_name: prod_app_311
      build:  
         context: .
         dockerfile: dockerfile311.prod
      command: python wsgi_sas14_311.py
      volumes: 
         - .:/usr/src/app/
      ports: 
         - "127.0.0.1:7001:7002"
      environment: 
         - TZ=Europe/Moscow
         - HTTP_PROXY=msc01-cfw01.pgk.rzd:9090
         - HTTPS_PROXY=msc01-cfw01.pgk.rzd:9090 
      network_mode: bridge   

networks: 
    net_nginx_prod: 
        driver: bridge
        ipam:
            config:
            - subnet: 172.17.188.0/24
            