version: '3.5'
services: 
   app:
      container_name: dev_front_ex
      build:  
         context: .
         dockerfile: dockerfile
      command: python wsgi_dev.py
      # command: gunicorn -w 1 -b 0.0.0.0:7007 wsgi:app  
      volumes: 
         - .:/usr/src/app/
      ports: 
         # - "127.0.0.1:7008:7007"
         - "7008:7007"
      # depends_on: 
      #    - redis   
      environment: 
         - TZ=Europe/Moscow
      networks: 
         - net_nginx      
   
   nginx:
      build:
         context: ./nginx
         dockerfile: dockerfile
      ports:
            - 7009:7009
      depends_on:
            - app    
      networks: 
         - net_nginx
networks: 
   net_nginx: 
      driver: bridge
      ipam:
         config:
           - subnet: 13.7.1.0/16
   
    # worker_1:
    #     build:  
    #         context: .
    #         dockerfile: dockerfile
    #     hostname: worker_1
    #     container_name: dev_worker_1

    #     entrypoint: celery
    #     # '-B' option start scheduler with worker, another option to start celery beat separately 
    #     command: worker -A restapi.celery -B -l INFO
    #     volumes:
    #         - .:/app
    #     depends_on:
    #         - redis
    #     network_mode: bridge
    #     environment: 
    #         - TZ=Europe/Moscow
    
    # worker_2:
    #     build:
    #         context: .
    #         dockerfile: dockerfile
    #     hostname: worker_2
    #     container_name: dev_worker_2


    #     entrypoint: celery
    #     command: worker -A restapi.celery -l INFO
    #     volumes:
    #         - ./restAPI:/opt/restapi/
    #     depends_on:
    #         - redis
    #     network_mode: bridge        

    # flower:  
    #     image: mher/flower
    #     container_name: dev_flower
    #     environment:
    #         - CELERY_BROKER_URL=redis://msc199-sdb04.domain.local:7038
    #         - FLOWER_PORT=7039
    #         - CELERY_TIMEZONE=Europe/Moscow
    #         - TZ=Europe/Moscow
    #     ports:  
    #        - 7039:7039   
    #     # command: ["flower", "--broker=redis://redis:7038/0", "--port=7039"]       
    #     network_mode: bridge
    #     depends_on: 
    #         - redis
            