version: '3.5'
services: 
    app:
        container_name: uva001_front
        build: 
            context: .
            dockerfile: dockerfile
        command: python manage.py
        volumes: 
           - .:/app
        ports:
           - "9103:9104"
        environment: 
           - TZ=Europe/Moscow
        network_mode: bridge