# Set version python 
FROM python:3.8
LABEL maintainer "Турганов Артем TurganovAI@pgkweb.ru"

# set workdir directory
WORKDIR /usr/src/app

# set TZ Moscow time
ENV TZ Europe/Moscow
RUN apt-get install tzdata
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone 

# install system dependencies
# RUN pip install --upgrade pip
# copy requirements and projects 
COPY . /usr/src/app/  

# install necessary python modules
RUN pip install --proxy=http://msc01-cfw01.pgk.rzd:9090 -r requirements.txt

# copy entrypoint.sh
# COPY ./entrypoint.sh /opt/restapi/entrypoint.sh

USER root

# run entrypoint.sh
# ENTRYPOINT ["sh", "/usr/src/app/entrypoint.sh"]

EXPOSE 7102
# EXPOSE {FLASK_PORT_PROD}