"""empty message

Revision ID: 3890dee046c1
Revises: 
Create Date: 2024-01-26 12:16:01.229827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3890dee046c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.String(length=80), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    info={'bind_key': 'log'}
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ldap_account', sa.Unicode(length=250), nullable=False),
    sa.Column('last_name', sa.Unicode(length=250), nullable=True),
    sa.Column('first_name', sa.Unicode(length=250), nullable=True),
    sa.Column('second_name', sa.Unicode(length=250), nullable=True),
    sa.Column('dept_id', sa.Unicode(length=1000), nullable=True),
    sa.Column('position', sa.Unicode(length=1000), nullable=True),
    sa.Column('email', sa.Unicode(length=250), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('roles_dashes',
    sa.Column('dash_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dash_id'], ['dash.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    info={'bind_key': None}
    )
    op.create_table('roles_reports',
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    info={'bind_key': None}
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    info={'bind_key': None}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('roles_reports')
    op.drop_table('roles_dashes')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('report')
    op.drop_table('log')
    op.drop_table('dash')
    # ### end Alembic commands ###
