"""empty message

Revision ID: b5a30e39f2e3
Revises: 864dedf2459b
Create Date: 2021-05-17 18:28:34.364184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a30e39f2e3'
down_revision = '864dedf2459b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dept_id',
               existing_type=sa.INTEGER(),
               type_=sa.Unicode(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dept_id',
               existing_type=sa.Unicode(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
