upstream app {
    server app:7008;
}

server {

    listen 7009;
    server_name analytics;

    location / {
        # proxy_pass http://ch-32.cgorod.pw:7008;
        proxy_pass http://app;

        # Do not change this
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


        # proxy_set_header X-NginX-Proxy true;
        # proxy_pass http://localhost:7008/;
        # proxy_redirect http://localhost:7008/ https://$server_name/;

    }

    location /static {
        # rewrite ^/static(.*) /$1 break;
        # root /static;
        proxy_pass http://app:7007/static;
    }
}

