"""empty message

Revision ID: 161ad874eaa9
Revises: b5a30e39f2e3
Create Date: 2021-06-11 16:24:14.910201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161ad874eaa9'
down_revision = 'b5a30e39f2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.Unicode(length=250), nullable=True))
    op.add_column('user', sa.Column('active', sa.Unicode(length=250), nullable=True))
    op.add_column('user', sa.Column('password', sa.Unicode(length=200), nullable=True))
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Unicode(length=250),
               existing_nullable=True)
    op.alter_column('user', 'second_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Unicode(length=250),
               existing_nullable=True)
    op.alter_column('user', 'dept_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Unicode(length=1000),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Unicode(length=250),
               existing_nullable=False)
    op.drop_column('user', 'role')
    op.drop_column('user', 'status')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'family_name')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'personnel_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('personnel_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('family_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.Unicode(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('user', 'dept_id',
               existing_type=sa.Unicode(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('user', 'second_name',
               existing_type=sa.Unicode(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.Unicode(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('user', 'password')
    op.drop_column('user', 'active')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
