"""empty message

Revision ID: 864dedf2459b
Revises: 
Create Date: 2021-05-05 16:53:39.643777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864dedf2459b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_number', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.Unicode(length=1000), nullable=True),
    sa.Column('family_name', sa.Unicode(length=100), nullable=True),
    sa.Column('first_name', sa.Unicode(length=100), nullable=True),
    sa.Column('second_name', sa.Unicode(length=100), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Unicode(length=1000), nullable=True),
    sa.Column('email', sa.Unicode(length=100), nullable=False),
    sa.Column('status', sa.Unicode(length=100), nullable=True),
    sa.Column('password_hash', sa.Unicode(length=200), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
